### ISSUE TITLE
Lagoon integration does not work with custom domains

### ISSUE THREAD

**Issue by serhat-ozkara** [lando/lagoon#20]
https://github.com/lando/lagoon/blob/5589e63e622ee895399408ff90678197b13a01aa/lib/api.js#L59

**Comment by serhat-ozkara** [comment]
This assumes all Lagoon instances are using api.(domain) and ssh.(domain) but one can use whatever domain for said lagoon services

**Comment by labboy0276** [comment]
@serhat-ozkara can you specify more about your use case, what urls you are trying to use and why.  This will us get a better picture of what is going on.

**Comment by serhat-ozkara** [comment]
Hello @labboy0276,

When using custom lagoon environments, lagoon does not necessarily have to use ssh.mydomain.com or api.mydomain.com subdomains.
One can use my-own-sobdomain.mydomain.com for SSH address and my-other-subdomain.mydomain.com for API endpoint.

But on api.js file, it is assumed that lagoon SSH is hosted on **SSH**.mydomain.com and API endpoint on **api**.mydomain.com.

So, sharing the domain on `${this.host}` for SSH and API endpoints for Lagoon integration,  incorrectly assumes this approach.
Users should be able to set their own addresses and domains for SSH and API endpoint addresses and ports.

Hardcoding subdomains like this: `https://api.${this.host}; ` or `ssh.${this.host}; ` limits the usability.

Thanks,

**Comment by labboy0276** [comment]
@serhat-ozkara ok this is something we can do in the future.  Most likely in Lando 4.

**Comment by almunnings** [comment]
Some or most of this information can be found in the user's ~/.lagoon.yml

```yml
cat ~/.lagoon.yml
current: govcms
default: amazeeio
lagoons:
    amazeeio:
        graphql: https://api.lagoon.amazeeio.cloud/graphql
        hostname: ssh.lagoon.amazeeio.cloud
        ui: https://dashboard.amazeeio.cloud
        kibana: https://logs.amazeeio.cloud/
        port: "32222"
        token: ""
        version: ""
        sshkey: ""
        sshportal: false
        publickeyidentities: []
    govcms:
        graphql: https://api-lagoon.govcms.amazee.io/graphql
        hostname: ssh-lagoon.govcms.amazee.io
        ui: ui-lagoon.govcms.amazee.io
        kibana: ""
        port: "30831"
        token: ""
        version: v2.23.0
        sshkey: ""
        sshportal: false
        publickeyidentities: []
updatecheckdisable: false
environmentfromdirectory: false
stricthostkeychecking: ""
```

Perhaps using lagooncli itself to configure the yml is the way to go?

EG
```yml
lagoon config add --lagoon govcms \
  --graphql https://api-lagoon.govcms.amazee.io/graphql \
  --hostname ssh-lagoon.govcms.amazee.io \
  --port 30831 \
  --ui ui-lagoon.govcms.amazee.io
```
