### ISSUE TITLE
Unable to add route via proxy when using Lagoon integration

### ISSUE THREAD

**Issue by tobybellwood** [lando/lagoon#6]
When using the Lando Lagoon integration, we should be able to add a custom route (either lndo.site or custom DNS) as per https://docs.lando.dev/guides/lando-101/lando-proxy.html

However, when trying this, even with a vanilla project (such as https://github.com/amazeeio/drupal-example-simple) the custom routes defined in the .lando.yml are not usable - but the default routes (eg mailhog) are.
```
name: drupal8-example-simple
recipe: lagoon
config:
  flavor: drupal
  build:
    - composer install
proxy:
  nginx:
    - abcde.lndo.site
```
![image](https://user-images.githubusercontent.com/4373945/109570993-12976580-7b3f-11eb-9f08-c6e416c1c836.png)

I have tested alongside this with a default (non-lagoon) Lando project and it all works as expected as per documentation.
