### ISSUE TITLE
Cannot read properties of undefined (reading 'services')

### ISSUE THREAD

**Issue by milkovsky** [lando/lagoon#83]
I ran `lando init --source lagoon`
At the end of the init process I see the Error:

> ERROR ==> Cannot read properties of undefined (reading 'services')

It happens after I execute any lando command, even `lando info`.

My `.lando.yml` file:

```
name: drupal-austria
recipe: lagoon
config:
  webroot: web
  composer_version: 2.8.1
  xdebug: true
  php: 8.3
  build:
    - composer install
```
