### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string.

### ISSUE THREAD

**Issue by amjad1233** [lando/lagoon#90]
When I run any lando command I get following error... Its like WSOD I can't go further with any other commands. 

```
TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received an instance of Array
    at Object.resolve (node:path:1169:7)
    at new LandoLando (/snapshot/core/builders/_lando.js)
    at new LandoAppserver (*********/.lando/plugins/@lando/lagoon/builders/_lagoon.js:60:7)
    at new LandoLagoonPhp (*********/.lando/plugins/@lando/lagoon/builders/lagoon-php-cli.js:40:7)
    at /snapshot/core/hooks/app-add-v3-services.js
    at arrayEach (/snapshot/core/node_modules/lodash/lodash.js:530:11)
    at Function.forEach (/snapshot/core/node_modules/lodash/lodash.js:9410:14)
    at /snapshot/core/hooks/app-add-v3-services.js
    at AsyncEvents.<anonymous> (/snapshot/core/app.js)
From previous event:
    at AsyncEvents.handle (/snapshot/core/lib/events.js)
    at /snapshot/core/lib/events.js
    at process.processImmediate (node:internal/timers:483:21)
From previous event:
    at AsyncEvents.emit (/snapshot/core/lib/events.js)
    at /snapshot/core/lib/app.js
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Excerpt from `.lando.yml`

```
name: xyz
recipe: lagoon

# Basic config.
config:
  flavor: drupal

# Post build steps.
events:
  post-start:
    - cli: composer install
    - cli: npm install
    - cli: npm run dev --dui
    - cli: npm run dev
```

Docker Desktop Version :  4.37.2 (179585)
Lando Version : 3.24.0
